apiVersion: v1
data:
  ### Example Aqua database password. Please change the password to what you set it to for your instance
  # To create your base64 password entry use 'echo -n <literal_db_password>| base64'
  # vis echo -n '0neP4ssW0rd$!' |base64 
  password: cGFzc3dvcmQ=
  # password base64 encoded
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: aqua-db-secret
  # Change namespace where appropriate.
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  ### Example Aqua Audit database password.  Please change the password to what you set it to for your instance
  password: cGFzc3dvcmQ=
  # password
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: audit-db-secret
    # Change namespace where appropriate.
  namespace: monitoring
type: Opaque
---