apiVersion: v1
data:
  ### Aqua database password. Please change the password to what you set it to for your instance
  password: password
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: aqua-db-secret
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  ### Aqua Audit database password.  Please change the password to what you set it to for your instance
  password: password
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: audit-db-secret
  namespace: monitoring
type: Opaque
---